name       : nheko
version    : 0.11.0
release    : 5
source     :
    - https://github.com/Nheko-Reborn/nheko/archive/refs/tags/v0.11.0.tar.gz : 4d39e283b5221cbd7aa7e6c8013267e1637e78d6133c8ff490e4464b0792477c
license    : GPL-2.0-or-later
homepage   : https://nheko-reborn.github.io/
component  : network.im
summary    : Desktop client for Matrix using Qt
description: |
    Desktop client for Matrix using Qt
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5Svg)
    - pkgconfig(coeurl)
    - pkgconfig(gstreamer-webrtc-1.0)
    - pkgconfig(libcmark)
    - pkgconfig(libevent_core)
    - pkgconfig(nlohmann_json)
    - pkgconfig(olm)
    - pkgconfig(re2)
    - pkgconfig(xcb-ewmh)
    - asciidoctor
    - lmdbxx
    - mtxclient-devel
    - qt5-tools-devel # linguist
    - qtkeychain-devel
rundeps    :
    - qt5-quickcontrols2
# clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Better-follow-FreeDesktop-specification.patch
    %patch -p1 < $pkgfiles/0001-Default-to-system-theme.patch

    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
